import type { Metadata } from "next";
import "./globals.css";
import { auth } from '@/auth'
import Navbar from "@/components/navbar";
import Footer from "@/components/footer/index"
import { SessionProvider } from 'next-auth/react'


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <SessionProvider session={session}>
      <html lang="en">
        <body className="bg-black">   <Navbar /> <main>{children}</main>
          <Footer />
        </body>
      </html>
    </SessionProvider>
  );
}
